[package]
name = "rsvg-render"
version = "0.1.0"
authors = ["biojet1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
